<div class="footer" data-footer=true>
	<div class="footer__container">
		<div class="footer__section">
			<ul class="footer__link">
				<li><a href="#">멤버십</a></li>
				<li><a href="#">사이버몰이용약관</a></li>
				<li><a href="#">개인정보처리</a></li>
				<li><a href="#">이용안내</a></li>
				<li><a href="#">반품주소</a></li>
				<li><a href="#">FAQ</a></li>
			</ul>
		</div>
		<div class="footer__section">
			<div class="footer__address">
				<p class="addr__info">압구정 플래그십 스토어<br>서울특별시 강남구 신사동 654-11</p>
				<p><a href="javascript:;" data-layer="footerMap" class="btn__map modal__show">MAP</a></p>
				<p class="cs__info">
					82) 070-7720-9093<br>
					12:00am ~ 20:00pm
				</p>
			</div>
		</div>
		<div class="footer__section">
			<ul class="footer__sns">
				<li><a href="#">Instagram</a></li>
				<li><a href="#">Facebook</a></li>
				<li><a href="#">Youtube</a></li>
				<li><a href="#">Kakaotalk</a></li>
				<li><a href="#">Blog</a></li>
			</ul>
		</div>
	</div>

	<!-- Funk Play -->
	<div class="footer__funkplay">
		<div class="footer__logo">
				<div class="footer__logo--item">
					<svg class="footer__logo--pc" id="Layer_1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1864 204">
						<!-- <defs>
							<style>.footer__first-logo{fill:#000;}</style>
						</defs> -->
						<g>
							<polygon class="footer__first-logo" points="2.5 199.83 2.5 .92 318.62 .92 318.62 45.33 49.6 45.33 49.6 75.88 318.62 75.88 318.62 120.56 49.6 120.56 49.6 199.83 2.5 199.83"/>
							<path d="M318.12,1.42V44.83H49.1v31.56H318.12v43.68H49.1v79.27H3V1.43H318.12m1-1.01H2V200.33H50.1V121.07H319.12v-45.68H50.1v-29.56H319.12V.42h0Z"/>
						</g>
						<g>
							<polygon class="footer__first-logo" points="667.78 199.83 529.39 66.68 529.39 199.83 479.21 199.83 479.21 .92 532.42 .92 668.08 127.31 668.08 .92 718.27 .92 718.27 199.83 667.78 199.83"/>
							<path d="M717.77,1.42V199.33h-49.78l-137.4-132.19-1.69-1.63V199.33h-49.18V1.42h52.51l134.67,125.48,1.68,1.57V1.42h49.19m1-1h-51.18V126.17h0L532.61,.42h-53.9V200.33h51.18V67.86h0l137.69,132.47h51.18V.42h.01Z"/>
						</g>
						<g>
							<polygon class="footer__first-logo" points="819.74 199.83 779.2 110.85 779.2 199.83 731.9 199.83 731.9 .92 779.2 .92 779.2 93.38 817.27 .92 877.5 .92 830.77 98.92 881.63 199.83 819.74 199.83"/>
							<path d="M876.71,1.42l-46.29,97.06-.21,.44,.22,.44,50.39,99.97h-60.76l-39.45-86.59-1.91-4.19v90.79h-46.3V1.43h46.3V95.92l1.92-4.68L817.59,1.43h59.12m1.59-1.01h-61.37l-37.23,90.43h0V.42h-48.3V200.33h48.3V113.15h0l39.71,87.18h63.02l-51.1-101.42L878.3,.42h0Z"/>
						</g>
						<g>
							<path class="footer__first-logo" d="M891.6,199.83V.92h244.68c48.07,0,71.44,21.11,71.44,64.52v2.69c0,43.17-24.04,65.06-71.44,65.06h-197.37v66.64h-47.31Zm47.31-110.51h196.54c15.19,0,22.89-7.22,22.89-21.46v-.81c0-14.42-7.7-21.73-22.89-21.73h-196.54v44Z"/>
							<path d="M1136.28,1.42c47.73,0,70.94,20.94,70.94,64.02v2.69c0,19.48-5.05,34.78-15.02,45.5-11.77,12.65-30.58,19.06-55.92,19.06h-197.87v66.64h-46.3V1.42h244.17m-197.87,88.4h197.04c15.52,0,23.39-7.39,23.39-21.96v-.81c0-14.75-7.87-22.23-23.39-22.23h-197.04v45M1136.28,.42h-245.18V200.33h48.3v-66.64h196.87c55.15,0,71.94-29.83,71.94-65.56v-2.69c.01-36.54-16.37-65.02-71.93-65.02h0Zm-196.87,88.4V45.83h196.04c15.55,0,22.39,7.52,22.39,21.23v.81c0,13.7-7.26,20.96-22.39,20.96h-196.04Z"/>
						</g>
						<g>
							<polygon class="footer__first-logo" points="1221.82 199.83 1221.82 .92 1273.5 .92 1273.5 150.16 1467 150.16 1467 199.83 1221.82 199.83"/>
							<path d="M1273,1.42V150.66h193.5v48.67h-244.18V1.42h50.68m1-1h-52.68V200.33h246.18v-50.67h-193.5V.42h0Z"/>
						</g>
						<g>
							<path class="footer__first-logo" d="M1651.92,199.83l-14.51-36.54h-94.18l-13.89,36.54h-48.06L1558.84,.92h61.93l82.1,198.91h-50.95Zm-91.87-80.69h59.93l-30.6-76.84-29.33,76.84Z"/>
							<path d="M1620.43,1.42l81.69,197.91h-49.86l-14.26-35.91-.25-.63h-94.87l-.25,.64-13.64,35.9h-46.98L1559.18,1.42h61.25m-61.11,118.22h61.38l-.55-1.37-29.85-74.97-.95-2.38-.91,2.4-28.61,74.97-.51,1.35M1621.1,.42h-62.61l-77.95,199.91h49.13l13.89-36.54h93.5l14.51,36.54h52.04L1621.1,.42h0Zm-60.33,118.22h0l28.61-74.97h0l29.85,74.97h-58.46Z"/>
						</g>
						<g>
							<polygon class="footer__first-logo" points="1733.96 199.83 1733.96 122.79 1651.89 .92 1710.59 .92 1758.75 74.95 1807.74 .92 1861.08 .92 1781.27 122.79 1781.27 199.83 1733.96 199.83"/>
							<path d="M1860.15,1.42l-79.22,120.98-.16,.25v76.68h-46.3V122.64l-.17-.25L1652.84,1.42h57.49l47.59,73.17,.83,1.28,.84-1.27L1808.01,1.43h52.14m1.85-1.01h-54.52l-48.72,73.62h0L1710.87,.42h-59.91l82.51,122.52h0v77.38h48.3V122.94h0L1862,.42h0Z"/>
						</g>
						<g>
							<path class="footer__first-logo" d="M398.94,203.08c-36.01,0-65.3-29.29-65.3-65.3V.92h46.79V139.18c0,9.3,6.74,17.34,15.68,18.68,.94,.14,1.89,.21,2.83,.21,10.21,0,18.51-8.3,18.51-18.51V.92h46.79V137.78c0,36.01-29.29,65.3-65.3,65.3Z"/>
							<path d="M463.74,1.42V137.78c0,35.73-29.07,64.8-64.8,64.8s-64.8-29.07-64.8-64.8V1.42h45.79V139.18c0,9.55,6.92,17.79,16.1,19.18,.96,.15,1.94,.22,2.91,.22,10.48,0,19.01-8.53,19.01-19.01V1.42h45.79m1-1h-47.79V139.57c0,9.9-8.1,18.01-18.01,18.01-.91,0-1.83-.07-2.76-.21-8.86-1.33-15.25-9.23-15.25-18.19V.42h-47.79V137.78c0,36.19,29.61,65.8,65.8,65.8h0c36.19,0,65.8-29.61,65.8-65.8V.42h0Z"/>
						</g>
					</svg>
					<svg class="footer__logo--mo" id="Layer_2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 724 340">
						<g>
							<g>
								<path class="footer__first-logo" d="M2.5,337.5V175.02H202.5c39.25,0,58.33,17.23,58.33,52.67v2.2c0,35.24-19.62,53.11-58.33,53.11H41v54.49H2.5Zm38.5-90.18H201.82c12.48,0,18.81-5.93,18.81-17.64v-.66c0-11.85-6.33-17.86-18.81-17.86H41v36.16Z"/>
								<path d="M202.5,175.52c38.91,0,57.83,17.07,57.83,52.17v2.2c0,34.91-19.46,52.61-57.83,52.61H40.5v54.49H3V175.51H202.5M40.5,247.81H201.82c12.81,0,19.31-6.1,19.31-18.14v-.66c0-12.18-6.5-18.36-19.31-18.36H40.5v37.16m162-73.29H2v163.48H41.5v-54.49H202.5c45.1,0,58.83-24.39,58.83-53.61v-2.2c0-29.89-13.39-53.18-58.83-53.18h0ZM41.5,246.81v-35.16H201.82c12.72,0,18.31,6.15,18.31,17.36v.66c0,11.21-5.93,17.14-18.31,17.14H41.5Z"/>
							</g>
							<g>
								<polygon class="footer__first-logo" points="272.54 337.5 272.54 175.02 314.62 175.02 314.62 297.07 398.89 297.07 398.89 337.5 272.54 337.5"/>
								<path d="M314.12,175.52v122.05h84.27v39.43h-125.35V175.52h41.08m1-1h-43.08v163.48h127.35v-41.43h-84.27v-122.05h0Z"/>
							</g>
							<g>
								<path class="footer__first-logo" d="M550.26,337.5l-11.87-29.88h-77.15l-11.36,29.88h-39.1l63.36-162.48h50.52l67.06,162.48h-41.46Zm-75.32-65.8h49.27l-25.16-63.18-24.11,63.18Z"/>
								<path d="M524.33,175.52l66.65,161.48h-40.38l-11.62-29.25-.25-.63h-77.83l-.25,.64-11.11,29.24h-38.03l62.97-161.48h49.85m-50.12,96.68h50.73l-.55-1.37-24.41-61.3-.95-2.38-.91,2.4-23.4,61.3-.51,1.35m50.79-97.68h-51.2l-63.75,163.48h40.18l11.36-29.88h76.46l11.87,29.88h42.55l-67.47-163.48h0Zm-49.34,96.68l23.4-61.3h0l24.41,61.3h-47.81Z"/>
							</g>
							<g>
								<polygon class="footer__first-logo" points="617.39 337.5 617.39 274.57 550.35 175.02 598.14 175.02 637.57 235.64 677.68 175.02 721.08 175.02 655.89 274.57 655.89 337.5 617.39 337.5"/>
								<path d="M720.15,175.52l-64.6,98.65-.16,.25v62.58h-37.5v-62.59l-.17-.25-66.43-98.64h46.57l38.87,59.75,.83,1.28,.84-1.27,39.54-59.76h42.21m1.85-1h-44.59l-39.84,60.21h0l-39.16-60.21h-49l67.48,100.2v63.28h39.5v-63.28l65.61-100.2h0Z"/>
							</g>
							</g>
							<g>
							<g>
								<polygon class="footer__first-logo" points="2.5 164.98 2.5 2.5 260.83 2.5 260.83 38.64 40.83 38.64 40.83 63.81 260.83 63.81 260.83 100.16 40.83 100.16 40.83 164.98 2.5 164.98"/>
								<path d="M260.33,3V38.13H40.33v26.17h220v35.35H40.33v64.82H3V2.99H260.33m1-.99H2V165.48H41.33V100.66h220V63.31H41.33v-24.17h220V2h0Z"/>
							</g>
							<g>
								<polygon class="footer__first-logo" points="546.5 164.98 433.2 55.98 433.2 164.98 392.34 164.98 392.34 2.5 435.72 2.5 546.79 105.99 546.79 2.5 587.65 2.5 587.65 164.98 546.5 164.98"/>
								<path d="M587.15,3V164.48h-40.45l-112.31-108.05-1.69-1.63v109.68h-39.86V3h42.69l110.09,102.56,1.68,1.57V3h39.85m1-1h-41.86V104.83h0L435.92,2h-44.08V165.48h41.86V57.16h0l112.6,108.33h41.86V2h0Z"/>
							</g>
							<g>
								<polygon class="footer__first-logo" points="677.44 164.98 637.48 92.24 637.48 164.98 598.98 164.98 598.98 2.5 637.48 2.5 637.48 78.07 675.42 2.5 721.18 2.5 679.64 82.54 721.19 164.98 677.44 164.98"/>
								<path d="M720.35,3l-41.04,79.08-.24,.45,.23,.46,41.07,81.49h-42.64l-38.87-70.77-1.88-3.42v74.19h-37.5V3h37.5V80.17l1.89-3.77L675.72,3h44.63m1.65-1h-46.89l-37.12,73.95h0V2h-39.5V165.48h39.5V94.19h0l39.16,71.29h44.85l-41.8-82.94h0L722,2h0Z"/>
							</g>
							<g>
								<path class="footer__first-logo" d="M326.61,167.64c-29.4,0-53.31-23.92-53.31-53.31V2.5h38.08V115.47c0,7.65,5.54,14.26,12.9,15.37,.77,.12,1.56,.18,2.33,.18,8.4,0,15.23-6.83,15.23-15.23V2.5h38.09V114.33c0,29.4-23.93,53.31-53.32,53.31Z"/>
								<path d="M379.42,3V114.33c0,29.12-23.69,52.81-52.81,52.81s-52.81-23.69-52.81-52.81V3h37.09V115.47c0,7.9,5.73,14.72,13.32,15.86,.8,.12,1.61,.18,2.4,.18,8.67,0,15.73-7.05,15.73-15.73V2.99h37.08m1-.99h-39.08V115.79c0,8.1-6.63,14.73-14.73,14.73-.74,0-1.49-.06-2.25-.17-7.24-1.09-12.47-7.55-12.47-14.87V2h-39.09V114.33c0,29.6,24.21,53.81,53.81,53.81h0c29.6,0,53.81-24.21,53.81-53.81V2h0Z"/>
							</g>
						</g>
					</svg>
				</div>
				<div class="footer__logo--item">
					<picture>
						<source media="(max-width: 1024px)" srcset="/assets/images/funkplay/footer_logo_mo_green.svg">
						<source media="(min-width: 1025px)" srcset="/assets/images/funkplay/footer_logo_pc_green.svg">
						<img src="/assets/images/funkplay/footer_logo_pc_green.svg" alt="">
					</picture>
				</div>
				<div class="footer__logo--item">
					<picture>
						<source media="(max-width: 1024px)" srcset="/assets/images/funkplay/footer_logo_mo_orange.svg">
						<source media="(min-width: 1025px)" srcset="/assets/images/funkplay/footer_logo_pc_orange.svg">
						<img src="/assets/images/funkplay/footer_logo_pc_orange.svg" alt="">
					</picture>
				</div>
				<div class="footer__logo--item">
					<picture>
						<source media="(max-width: 1024px)" srcset="/assets/images/funkplay/footer_logo_mo_yellow.svg">
						<source media="(min-width: 1025px)" srcset="/assets/images/funkplay/footer_logo_pc_yellow.svg">
						<img src="/assets/images/funkplay/footer_logo_pc_yellow.svg" alt="">
					</picture>
				</div>
				<div class="footer__logo--item">
					<picture>
						<source media="(max-width: 1024px)" srcset="/assets/images/funkplay/footer_logo_mo_purple.svg">
						<source media="(min-width: 1025px)" srcset="/assets/images/funkplay/footer_logo_pc_purple.svg">
						<img src="/assets/images/funkplay/footer_logo_pc_purple.svg" alt="">
					</picture>
				</div>
				<div class="footer__logo--item">
					<picture>
						<source media="(max-width: 1024px)" srcset="/assets/images/funkplay/footer_logo_mo_green.svg">
						<source media="(min-width: 1025px)" srcset="/assets/images/funkplay/footer_logo_pc_green.svg">
						<img src="/assets/images/funkplay/footer_logo_pc_green.svg" alt="">
					</picture>
				</div>
				<div class="footer__logo--item">
					<picture>
						<source media="(max-width: 1024px)" srcset="/assets/images/funkplay/footer_logo_mo_orange.svg">
						<source media="(min-width: 1025px)" srcset="/assets/images/funkplay/footer_logo_pc_orange.svg">
						<img src="/assets/images/funkplay/footer_logo_pc_orange.svg" alt="">
					</picture>
				</div>
				<div class="footer__logo--item">
					<picture>
						<source media="(max-width: 1024px)" srcset="/assets/images/funkplay/footer_logo_mo_yellow.svg">
						<source media="(min-width: 1025px)" srcset="/assets/images/funkplay/footer_logo_pc_yellow.svg">
						<img src="/assets/images/funkplay/footer_logo_pc_yellow.svg" alt="">
					</picture>
				</div>
				<div class="footer__logo--item">
					<picture>
						<source media="(max-width: 1024px)" srcset="/assets/images/funkplay/footer_logo_mo_purple.svg">
						<source media="(min-width: 1025px)" srcset="/assets/images/funkplay/footer_logo_pc_purple.svg">
						<img src="/assets/images/funkplay/footer_logo_pc_purple.svg" alt="">
					</picture>
				</div>
				<div class="footer__logo--item">
					<picture>
						<source media="(max-width: 1024px)" srcset="/assets/images/funkplay/footer_logo_mo_green.svg">
						<source media="(min-width: 1025px)" srcset="/assets/images/funkplay/footer_logo_pc_green.svg">
						<img src="/assets/images/funkplay/footer_logo_pc_green.svg" alt="">
					</picture>
				</div>
		</div>

		<a href="/funkplay/list.html" class="btn__funkplay">
				<div class="marquee">
						<div class="marquee__mask">
								<p class="marquee__loop">
										<span class="marquee__text">CLICK!</span>
										<span class="marquee__text">CLICK!</span>
										<span class="marquee__text">CLICK!</span>
										<span class="marquee__text">CLICK!</span>
								</p>
								<p class="marquee__loop">
										<span class="marquee__text">CLICK!</span>
										<span class="marquee__text">CLICK!</span>
										<span class="marquee__text">CLICK!</span>
										<span class="marquee__text">CLICK!</span>
								</p>
								<p class="marquee__loop">
										<span class="marquee__text">CLICK!</span>
										<span class="marquee__text">CLICK!</span>
										<span class="marquee__text">CLICK!</span>
										<span class="marquee__text">CLICK!</span>
								</p>
								<p class="marquee__loop">
										<span class="marquee__text">CLICK!</span>
										<span class="marquee__text">CLICK!</span>
										<span class="marquee__text">CLICK!</span>
										<span class="marquee__text">CLICK!</span>
								</p>
						</div>
				</div>
		</a>
		<!-- TODO: Task -->
	</div>
    <!-- // Funk Play -->

	<!-- <div class="footer__funkplay">
		<div class="img_funkplay"></div>
		<a href="#" class="btn__funkplay">
			<div class="marquee">
				<div class="marquee__mask">
					<p class="marquee__loop">
						<span class="marquee__text">CLICK!</span>
						<span class="marquee__text">CLICK!</span>
						<span class="marquee__text">CLICK!</span>
						<span class="marquee__text">CLICK!</span>
					</p>
					<p class="marquee__loop">
						<span class="marquee__text">CLICK!</span>
						<span class="marquee__text">CLICK!</span>
						<span class="marquee__text">CLICK!</span>
						<span class="marquee__text">CLICK!</span>
					</p>
					<p class="marquee__loop">
						<span class="marquee__text">CLICK!</span>
						<span class="marquee__text">CLICK!</span>
						<span class="marquee__text">CLICK!</span>
						<span class="marquee__text">CLICK!</span>
					</p>
					<p class="marquee__loop">
						<span class="marquee__text">CLICK!</span>
						<span class="marquee__text">CLICK!</span>
						<span class="marquee__text">CLICK!</span>
						<span class="marquee__text">CLICK!</span>
					</p>
				</div>
			</div>
		</a>
	</div> -->
	<div class="footer__cs">
		<div class="marquee">
			<div class="marquee">
				<div class="marquee__mask">
					<p class="marquee__loop">
						<span class="marquee__text">MON-FRI, 10:00AM ~ 18:00</span>
						<span class="marquee__text">cs@instantfunk.kr</span>
						<span class="marquee__text">MON-FRI, 10:00AM ~ 18:00</span>
						<span class="marquee__text">cs@instantfunk.kr</span>
					</p>
					<p class="marquee__loop">
						<span class="marquee__text">MON-FRI, 10:00AM ~ 18:00</span>
						<span class="marquee__text">cs@instantfunk.kr</span>
						<span class="marquee__text">MON-FRI, 10:00AM ~ 18:00</span>
						<span class="marquee__text">cs@instantfunk.kr</span>
					</p>
					<p class="marquee__loop">
						<span class="marquee__text">MON-FRI, 10:00AM ~ 18:00</span>
						<span class="marquee__text">cs@instantfunk.kr</span>
						<span class="marquee__text">MON-FRI, 10:00AM ~ 18:00</span>
						<span class="marquee__text">cs@instantfunk.kr</span>
					</p>
					<p class="marquee__loop">
						<span class="marquee__text">MON-FRI, 10:00AM ~ 18:00</span>
						<span class="marquee__text">cs@instantfunk.kr</span>
						<span class="marquee__text">MON-FRI, 10:00AM ~ 18:00</span>
						<span class="marquee__text">cs@instantfunk.kr</span>
					</p>
				</div>
			</div>
		</div>
	</div>
	<div class="footer_copyright">
		<div class="footer__section">
			<p>© INSTATNFUNK. ALL RIGHTS RESERVED 2022</p>
		</div>
		<div class="footer__section">
			<p><span>사업자등록번호 231-88-00766</span> <span>확인 통신판매신고 2018-서울강남-00068</span> <span>대표 신재혁 개인정보관리책임자 김요필</span></p>
		</div>
		<div class="footer__section">
			<p>©Simplexinternet</p>
		</div>
	</div>
	
</div>

<!-- 반품주소 팝업 -->
<div id="footerMap" class="layer__body footer_map">
	<div class="layer__wrap">
		<div class="layer__close">
			<a href="javascript:;" data-layer="footerMap" class="btn__close modal__hide">
				<svg class="svg-ico">
					<use xlink:href="@@webrootassets/images/ico.svg#ico_close"></use>
				</svg>
				<span class="a11y">닫기</span>
			</a>
		</div>
		<div class="layer__content">
			<dl class="return__addr">
				<dt>반품주소</dt>
				<dd>
				상품을 보내시기 전에 <a href="#">ORDER</a> 페이지에서 반품접수를 먼저 해주셔야 합니다.
				</dd>
			</dl>
			<ul class="return__addr--info">
				<li>
					<p class="addr__title">택배사</p>
					<p class="addr__info">CJ 대한 통운</p>
				</li>
				<li>
					<p class="addr__title">우편번호</p>
					<p class="addr__info">12015</p>
				</li>
				<li>
					<p class="addr__title">주소</p>
					<p class="addr__info">경기도 남양주시 진정읍 자현리 616번지 매쉬코리아</p>
				</li>
			</ul>
		</div>
	</div>
</div>