<div class="footer">
	<div class="footer__container">
		<div class="footer__section">
			<ul class="footer__link">
				<li><a href="#">멤버십</a></li>
				<li><a href="#">사이버몰이용약관</a></li>
				<li><a href="#">개인정보처리</a></li>
				<li><a href="#">이용안내</a></li>
				<li><a href="#">반품주소</a></li>
				<li><a href="#">FAQ</a></li>
			</ul>
		</div>
		<div class="footer__section">
			<div class="footer__address">
				<p class="addr__info">압구정 플래그십 스토어<br>서울특별시 강남구 신사동 654-11</p>
				<p><a href="javascript:;" data-layer="footerMap" class="btn__map modal__show">MAP</a></p>
				<p class="cs__info">
					82) 070-7720-9093<br>
					12:00am ~ 20:00pm
				</p>
			</div>
		</div>
		<div class="footer__section">
			<ul class="footer__sns">
				<li><a href="#">Instagram</a></li>
				<li><a href="#">Facebook</a></li>
				<li><a href="#">Youtube</a></li>
				<li><a href="#">Kakaotalk</a></li>
				<li><a href="#">Blog</a></li>
			</ul>
		</div>
	</div>

	<div class="footer__funkplay">
		<div class="img_funkplay"></div>
		<a href="#" class="btn__funkplay">
			<div class="marquee">
				<div class="marquee__mask">
					<p class="marquee__loop">
						<span class="marquee__text">CLICK!</span>
						<span class="marquee__text">CLICK!</span>
						<span class="marquee__text">CLICK!</span>
						<span class="marquee__text">CLICK!</span>
					</p>
					<p class="marquee__loop">
						<span class="marquee__text">CLICK!</span>
						<span class="marquee__text">CLICK!</span>
						<span class="marquee__text">CLICK!</span>
						<span class="marquee__text">CLICK!</span>
					</p>
					<p class="marquee__loop">
						<span class="marquee__text">CLICK!</span>
						<span class="marquee__text">CLICK!</span>
						<span class="marquee__text">CLICK!</span>
						<span class="marquee__text">CLICK!</span>
					</p>
					<p class="marquee__loop">
						<span class="marquee__text">CLICK!</span>
						<span class="marquee__text">CLICK!</span>
						<span class="marquee__text">CLICK!</span>
						<span class="marquee__text">CLICK!</span>
					</p>
				</div>
			</div>
		</a>
	</div>
	<div class="footer__cs">
		<div class="marquee">
			<div class="marquee">
				<div class="marquee__mask">
					<p class="marquee__loop">
						<span class="marquee__text">MON-FRI, 10:00AM ~ 18:00</span>
						<span class="marquee__text">cs@instantfunk.kr</span>
						<span class="marquee__text">MON-FRI, 10:00AM ~ 18:00</span>
						<span class="marquee__text">cs@instantfunk.kr</span>
					</p>
					<p class="marquee__loop">
						<span class="marquee__text">MON-FRI, 10:00AM ~ 18:00</span>
						<span class="marquee__text">cs@instantfunk.kr</span>
						<span class="marquee__text">MON-FRI, 10:00AM ~ 18:00</span>
						<span class="marquee__text">cs@instantfunk.kr</span>
					</p>
					<p class="marquee__loop">
						<span class="marquee__text">MON-FRI, 10:00AM ~ 18:00</span>
						<span class="marquee__text">cs@instantfunk.kr</span>
						<span class="marquee__text">MON-FRI, 10:00AM ~ 18:00</span>
						<span class="marquee__text">cs@instantfunk.kr</span>
					</p>
					<p class="marquee__loop">
						<span class="marquee__text">MON-FRI, 10:00AM ~ 18:00</span>
						<span class="marquee__text">cs@instantfunk.kr</span>
						<span class="marquee__text">MON-FRI, 10:00AM ~ 18:00</span>
						<span class="marquee__text">cs@instantfunk.kr</span>
					</p>
				</div>
			</div>
		</div>
	</div>
	<div class="footer_copyright">
		<div class="footer__section">
			<p>© INSTATNFUNK. ALL RIGHTS RESERVED 2022</p>
		</div>
		<div class="footer__section">
			<p><span>사업자등록번호 231-88-00766</span> <span>확인 통신판매신고 2018-서울강남-00068</span> <span>대표 신재혁 개인정보관리책임자 김요필</span></p>
		</div>
		<div class="footer__section">
			<p>©Simplexinternet</p>
		</div>
	</div>
	
</div>

<!-- 반품주소 팝업 -->
<div id="footerMap" class="layer__body footer_map">
	<div class="layer__wrap">
		<div class="layer__close"><a href="javascript:;" data-layer="footerMap" class="btn__close modal__hide"><span class="a11y">닫기</span></a></div>
		<div class="layer__content">
			<dl class="return__addr">
				<dt>반품주소</dt>
				<dd>
				상품을 보내시기 전에 <a href="#">ORDER</a> 페이지에서 반품접수를 먼저 해주셔야 합니다.
				</dd>
			</dl>
			<ul class="return__addr--info">
				<li>
					<p class="addr__title">택배사</p>
					<p class="addr__info">CJ 대한 통운</p>
				</li>
				<li>
					<p class="addr__title">우편번호</p>
					<p class="addr__info">12015</p>
				</li>
				<li>
					<p class="addr__title">주소</p>
					<p class="addr__info">경기도 남양주시 진정읍 자현리 616번지 매쉬코리아</p>
				</li>
			</ul>
		</div>
	</div>
</div>