	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>@@pagetitle</title>

	<script src="/web/assets/js/jquery-3.6.0.min.js"></script>
	<script src="/web/assets/js/swiper-bundle.min.js"></script>
	<script src="/web/assets/js/ui.js"></script>
	<link rel="stylesheet" href="/web/assets/css/ui.css">